// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Laptop_price_predictor
{
    public partial class Model
    {
        /// <summary>
        /// model input class for Model.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Category")]
            public float Category { get; set; }

            [ColumnName(@"Screen Size(in inches)")]
            public float Screen_Size_in_inches_ { get; set; }

            [ColumnName(@"Screen Resolution")]
            public float Screen_Resolution { get; set; }

            [ColumnName(@"CPU")]
            public float CPU { get; set; }

            [ColumnName(@"GHz")]
            public float GHz { get; set; }

            [ColumnName(@"RAM(IN GB)")]
            public float RAM_IN_GB_ { get; set; }

            [ColumnName(@"Storage(Gb)")]
            public float Storage_Gb_ { get; set; }

            [ColumnName(@"GPU")]
            public float GPU { get; set; }

            [ColumnName(@"OS")]
            public float OS { get; set; }

            [ColumnName(@"Weight (in kg)")]
            public float Weight__in_kg_ { get; set; }

            [ColumnName(@"Price (in php)")]
            public float Price__in_php_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Model.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Category")]
            public float Category { get; set; }

            [ColumnName(@"Screen Size(in inches)")]
            public float Screen_Size_in_inches_ { get; set; }

            [ColumnName(@"Screen Resolution")]
            public float Screen_Resolution { get; set; }

            [ColumnName(@"CPU")]
            public float CPU { get; set; }

            [ColumnName(@"GHz")]
            public float GHz { get; set; }

            [ColumnName(@"RAM(IN GB)")]
            public float RAM_IN_GB_ { get; set; }

            [ColumnName(@"Storage(Gb)")]
            public float Storage_Gb_ { get; set; }

            [ColumnName(@"GPU")]
            public float GPU { get; set; }

            [ColumnName(@"OS")]
            public float OS { get; set; }

            [ColumnName(@"Weight (in kg)")]
            public float Weight__in_kg_ { get; set; }

            [ColumnName(@"Price (in php)")]
            public float Price__in_php_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Model.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
